### PR TITLE
Lock client fixes

### LINKED ISSUE #21: The new objectDescriptor object.
This issue demands a new descriptor type `ObjectDescriptor` and `LockDescriptor` over the old `SimpleDescriptor`.

`SimpleDescriptor` has both the `ID` of the object to be acquired and the `Owner` that needs to acquire it. While this makes sense for having complete details about the lock being acquired and that needs to be maintained in the map, this doesn't make sense when the lock is being pounced on. The lock that has to be pounced on cannot be described by a `SimpleDescriptor` but needs just the description of the object.

Thus, on separating these concerns I propose the following:
* `SimpleDescriptor` gets a more meaningful name - `LockDescriptor` and has all data fields the same.
* A new descriptor `ObjectDescriptor` that has only the `ID` of the object in it.

This suffices the needs of the pouncing feature.

Edit: The main reason for the move is the `pouncers` map in the lock client that needs to map the `ObjectDescriptors` to the slice of the pouncers and not a `SimpleDescriptor` to the slice of owners. The move is proposed so that  in the future we can easily add fields to the struct of `ObjectDescriptor` and have our code function.

Edit 2: This also means that now, Watch can also take in `ObjectDescriptor` as it's argument instead of the `SimpleDescriptor`.

### PR DESCRIPTION
**Pull request by SUMUKHA-PK**
This PR aligns the lock client to a common erroring methodology and makes it robust for implementations to come.

Also closed #21

### CODE REVIEW

File: internal/cache/cache.go [hunk 1]
```diff
@@ -6,7 +6,7 @@ type Cache interface {
 	// Getting the object makes it the most recently used object
```
Comment (suraj44) [inline internal/cache/cache.go:6]: just double checking: are you happy with the current definition of GetElement - 'getting the desired object from the cache' ?

File: internal/cache/lru_cache.go [hunk 2]
```diff
@@ -43,17 +47,22 @@ func NewLRUCache(capacity int) *LRUCache {
 	}
 }
 
-// GetElement gets an element from the cache.
+// GetElement gets an element from the cache. It returns
+// the associated data with the element with an error.
```
Comment (suraj44) [inline internal/cache/lru_cache.go:51]: associated data? why not specify that the owner is being returned?

File: internal/cache/lru_cache.go [hunk 3]
```diff
@@ -89,28 +93,31 @@ func (lru *LRUCache) GetElement(element interface{}) error {
 // Removal of the LRU is done my deleting the tail node,
 // making place for a new node.
 func (lru *LRUCache) PutElement(element interface{}) error {
+	lru.mu.Lock()
+	defer lru.mu.Unlock()
 	if !lru.full {
```
Comment (suraj44) [inline internal/cache/lru_cache.go:100]: Add a comment on each of these ifs describing the condition being evaluated. That would make reading through the code a lot better!

File: internal/cache/lru_cache.go [hunk 4]
```diff
@@ -89,28 +93,31 @@ func (lru *LRUCache) GetElement(element interface{}) error {
...
 		if lru.dll.Head == nil {
```
Comment (suraj44) [inline internal/cache/lru_cache.go:101]: same as above

File: internal/cache/lru_cache.go [hunk 5]
```diff
@@ -89,28 +93,31 @@ func (lru *LRUCache) GetElement(element interface{}) error {
...
 			lru.dll.InsertNodeToRight(lru.dll.Head, element.(*SimpleKey))
```
Comment (suraj44) [inline internal/cache/lru_cache.go:102]: what happens if this is not done?
would it still work?

File: internal/cache/lru_cache.go [hunk 6]
```diff
@@ -142,8 +151,9 @@ func (lru *LRUCache) RemoveElement(element interface{}) error {
 		} else if lru.tail == nodeOfKey {
 			lru.tail = nodeOfKey.LeftNode.(*DLLNode)
 		}
+		lru.size--
```
Comment (suraj44) [inline internal/cache/lru_cache.go:158]: nice catch :P

File: internal/lockclient/client.go [hunk 7]
```diff
@@ -4,7 +4,13 @@ import "github.com/SystemBuilders/LocKey/internal/lockservice"
 
 // Client describes a client that can be used to interact with
 // the Lockey lockservice. The client can start the lockservice
-// and interact acquire and release locks by making calls to it.
+// and interact by making calls to it.
+//
+// The client has the ability to start the lockservice from its
```
Comment (suraj44) [inline internal/lockclient/client.go:9]: Has this functionality been added yet?

File: run.sh [hunk 8]
```diff
@@ -1 +0,0 @@
-go build -o main ./cmd/...  && ./main
```
Comment (suraj44) [inline run.sh:1]: is this file empty? 
it should either be deleted or another command should be added

File: internal/routing/routing.go [hunk 9]
```diff
@@ -9,20 +9,20 @@ import (
 
 // SetupRouting adds all the routes on the http server.
 func SetupRouting(ls *lockservice.SimpleLockService, r *mux.Router) *mux.Router {
-	r.HandleFunc("/acquire", makeAcquireHandler(ls)).Methods(http.MethodPost)
-	r.HandleFunc("/checkAcquire", makeCheckAcquiredHandler(ls)).Methods(http.MethodPost)
+	r.HandleFunc("/acquire", makeacquireHandler(ls)).Methods(http.MethodPost)
+	r.HandleFunc("/checkacquire", makeCheckacquiredHandler(ls)).Methods(http.MethodPost)
```
Comment (suraj44) [inline internal/routing/routing.go]: why are the 'a's made lower case here but for checkRelease, the 'R's are in upper case?

also why have the 'a's been made to lower case?

File: internal/lockclient/client.go [hunk 10]
```diff
@@ -28,3 +34,18 @@ type Config interface {
...
+// These are the states of a lock.
+const (
+	acquire State = iota
+	Release
+)
+
+// Lock includes the state of the lock and the owner.
+type Lock struct {
+	Owner     string
+	LockState State
```
Comment (suraj44) [inline internal/lockclient/client.go]: Where is this being used?

File: internal/lockclient/errors.go [hunk 11]
```diff
@@ -0,0 +1,12 @@
...
+
+// Error provides constant error strings to the driver functions.
+type Error string
+
+func (e Error) Error() string { return string(e) }
+
+// Constant errors.
+// Rule of thumb, all errors start with a small letter and end with no full stop.
+const (
+	ErrorObjectAlreadyPouncedOn = Error("the object already has a minimum of one pouncer")
```
Comment (suraj44) [inline internal/lockclient/errors.go]: Pounce related error. Should be removed?

File: internal/lockclient/simple_client.go [hunk 12]
```diff
@@ -16,12 +17,14 @@ var _ Config = (*lockservice.SimpleConfig)(nil)
...
-	config lockservice.SimpleConfig
-	cache  cache.LRUCache
+	config *lockservice.SimpleConfig
+	cache  *cache.LRUCache
+	mu     sync.Mutex
 }
 
-// NewSimpleKey returns a new SimpleKey of the given value.
-func NewSimpleClient(config lockservice.SimpleConfig, cache cache.LRUCache) *SimpleClient {
+// NewSimpleClient returns a new SimpleKey of the given value.
```
Comment (suraj44) [inline internal/lockclient/simple_client.go]: Returns a `SimpleKey`?? I think that needs to be changed

File: internal/lockclient/simple_client.go [hunk 13]
```diff
@@ -30,21 +33,34 @@ func NewSimpleClient(config lockservice.SimpleConfig, cache cache.LRUCache) *Sim
...
+// on the lock service.
+// The errors involved may be due the HTTP errors or the lockservice errors.
+//
+// Currently acquire doesn't order the user processes that request for the lock.
+func (sc *SimpleClient) acquire(d lockservice.Descriptors) error {
+	// Check for existance of a cache and check
+	// if the element is in the cache.
+	if sc.cache != nil {
+		_, err := sc.getFromCache(lockservice.ObjectDescriptor{ObjectID: d.ID()})
+		// Since there can be network errors, we have this double check.
```
Comment (suraj44) [inline internal/lockclient/simple_client.go]: how does getting from the cache involve network errors?

File: internal/lockclient/simple_client.go [hunk 14]
```diff
@@ -103,3 +133,91 @@ func (sc *SimpleClient) Release(d lockservice.Descriptors) error {
...
+}
+
+// getFromCache checks the lock status on the descriptor in the cache.
+// This function returns an error if the cache doesn't exist or the
+// file is NOT acquired.
+func (sc *SimpleClient) getFromCache(d lockservice.ObjectDescriptor) (string, error) {
+	if sc.cache != nil {
+		owner, err := sc.cache.GetElement(cache.NewSimpleKey(d.ObjectID, ""))
+		if err != nil {
+			return "", lockservice.ErrCheckacquireFailure
```
Comment (suraj44) [inline internal/lockclient/simple_client.go]: ErrCheckacquireFailure is "file is not acquired". That doesn't seem relevant here.

Instead shouldn't the error being returned ineidate that the element doesn't exist in the cache?

File: internal/lockclient/simple_client.go [hunk 15]
```diff
@@ -30,21 +33,34 @@ func NewSimpleClient(config lockservice.SimpleConfig, cache cache.LRUCache) *Sim
...
+// The errors involved may be due the HTTP errors or the lockservice errors.
+//
+// Currently acquire doesn't order the user processes that request for the lock.
+func (sc *SimpleClient) acquire(d lockservice.Descriptors) error {
+	// Check for existance of a cache and check
+	// if the element is in the cache.
+	if sc.cache != nil {
+		_, err := sc.getFromCache(lockservice.ObjectDescriptor{ObjectID: d.ID()})
+		// Since there can be network errors, we have this double check.
+		if err != nil && err != lockservice.ErrCheckacquireFailure {
```
Comment (suraj44) [inline internal/lockclient/simple_client.go]: I've requested a change within the implementation of the `getFromCache()` function. The corresponding change would have to be made here.

File: internal/lockclient/simple_client.go [hunk 16]
```diff
@@ -54,47 +70,61 @@ func (sc *SimpleClient) Acquire(d lockservice.Descriptors) error {
...
-
 	if resp.StatusCode != 200 {
 		return errors.New(strings.TrimSpace(string(body)))
 	}
-	err = sc.cache.PutElement(cache.NewSimpleKey(d.ID()))
-	if err != nil {
-		return err
-	}
 
+	if sc.cache != nil {
```
Comment (suraj44) [inline internal/lockclient/simple_client.go:84]: nice!

File: internal/lockclient/simple_client.go [hunk 17]
```diff
@@ -54,47 +70,61 @@ func (sc *SimpleClient) Acquire(d lockservice.Descriptors) error {
...
+		err := sc.addToCache(d)
+		if err != nil {
+			return err
+		}
+	}
 	return nil
 }
 
-// Release makes a HTTP call to the lockserver and acquires the lock.
+// Release makes an HTTP call to the lockserver and acquires the lock.
```
Comment (suraj44) [inline internal/lockclient/simple_client.go]: shouldn't it be 'releases the lock'?

File: internal/lockclient/simple_client.go [hunk 18]
```diff
@@ -54,47 +70,61 @@ func (sc *SimpleClient) Acquire(d lockservice.Descriptors) error {
...
 	resp, err := client.Do(req)
-
 	if err != nil {
 		return (err)
 	}
 	defer resp.Body.Close()
 
-	body, _ := ioutil.ReadAll(resp.Body)
-
+	body, err := ioutil.ReadAll(resp.Body)
```
Comment (suraj44) [inline internal/lockclient/simple_client.go:116]: nice!

File: internal/lockclient/simple_client.go [hunk 19]
```diff
@@ -103,3 +133,91 @@ func (sc *SimpleClient) Release(d lockservice.Descriptors) error {
...
 }
+
+// Checkacquire checks for acquisition of lock and returns the owner if the lock
+// is already acquired.
+// The errors returned can be due to HTTP errors or marshalling errors.
+// A "file is not acquired" error is returned if so and no error and an owner is
+// returned if the object is acquired.
+func (sc *SimpleClient) Checkacquire(d lockservice.ObjectDescriptor) (string, error) {
+	if sc.cache != nil {
+		owner, err := sc.getFromCache(d)
```
Comment (suraj44) [inline internal/lockclient/simple_client.go]: can't `sc.getFromCache(d)` be returned straightaway? The next few lines seem to be a repetition of the code already present in that function

File: internal/lockclient/simple_client.go [hunk 20]
```diff
@@ -103,3 +133,91 @@ func (sc *SimpleClient) Release(d lockservice.Descriptors) error {
...
+		if err != nil {
+			return "", err
+		}
+		return owner, nil
+	}
+
+	endPoint := sc.config.IPAddr + ":" + sc.config.PortAddr + "/checkacquire"
+	data := lockservice.LockCheckRequest{FileID: d.ObjectID}
```
Comment (suraj44) [inline internal/lockclient/simple_client.go:150]: Is a new type really needed for a `checkAcquire()` request?

File: internal/lockclient/simple_client_test.go [hunk 21]
```diff
@@ -36,32 +36,32 @@ func TestAcquireandRelease(t *testing.T) {
...
 		size := 5
 		cache := cache.NewLRUCache(size)
-		sc := NewSimpleClient(*scfg, *cache)
+		sc := NewSimpleClient(scfg, cache)
 
-		d := lockservice.NewSimpleDescriptor("test", "owner")
+		d := lockservice.NewLockDescriptor("test", "owner")
 
-		got := sc.Acquire(d)
+		got := sc.acquire(d)
```
Comment (suraj44) [inline internal/lockclient/simple_client_test.go]: Shouldn't `Acquire()` be called and not `acquire()`?

File: internal/lockclient/simple_client_test.go [hunk 22]
```diff
@@ -36,32 +36,32 @@ func TestAcquireandRelease(t *testing.T) {
...
 		var want error
 		if got != want {
 			t.Errorf("acquire: got %q want %q", got, want)
 		}
 
-		d = lockservice.NewSimpleDescriptor("test1", "owner")
+		d = lockservice.NewLockDescriptor("test1", "owner")
 
-		got = sc.Acquire(d)
+		got = sc.acquire(d)
```
Comment (suraj44) [inline internal/lockclient/simple_client_test.go]: same as above

File: internal/lockclient/simple_client_test.go [hunk 23]
```diff
@@ -73,23 +73,23 @@ func TestAcquireandRelease(t *testing.T) {
...
 		size := 5
 		cache := cache.NewLRUCache(size)
-		sc := NewSimpleClient(*scfg, *cache)
+		sc := NewSimpleClient(scfg, cache)
 
-		d := lockservice.NewSimpleDescriptor("test", "owner")
+		d := lockservice.NewLockDescriptor("test", "owner")
 
-		got := sc.Acquire(d)
+		got := sc.acquire(d)
```
Comment (suraj44) [inline internal/lockclient/simple_client_test.go]: same as above

File: internal/lockclient/simple_client_test.go [hunk 24]
```diff
@@ -73,23 +73,23 @@ func TestAcquireandRelease(t *testing.T) {
...
 		var want error
 		if got != want {
 			t.Errorf("acquire: got %q want %q", got, want)
 		}
 
-		got = sc.Acquire(d)
-		want = lockservice.ErrFileAcquired
+		got = sc.acquire(d)
```
Comment (suraj44) [inline internal/lockclient/simple_client_test.go]: same as above

File: internal/lockclient/simple_client_test.go [hunk 25]
```diff
@@ -99,40 +99,115 @@ func TestAcquireandRelease(t *testing.T) {
...
-		size := 1
+		size := 2
 		cache := cache.NewLRUCache(size)
-		sc := NewSimpleClient(*scfg, *cache)
+		sc := NewSimpleClient(scfg, cache)
 
-		d := lockservice.NewSimpleDescriptor("test", "owner1")
-		got := sc.Acquire(d)
+		d := lockservice.NewLockDescriptor("test", "owner1")
+		got := sc.acquire(d)
```
Comment (suraj44) [inline internal/lockclient/simple_client_test.go]: same as above

File: internal/lockclient/simple_client_test.go [hunk 26]
```diff
@@ -99,40 +99,115 @@ func TestAcquireandRelease(t *testing.T) {
...
 		got = sc.Release(d)
 		want = lockservice.ErrUnauthorizedAccess
 		if got != want {
 			t.Errorf("acquire: got %v want %v", got, want)
 		}
 
-		d = lockservice.NewSimpleDescriptor("test2", "owner1")
-		got = sc.Acquire(d)
+		d = lockservice.NewLockDescriptor("test2", "owner1")
+		got = sc.acquire(d)
```
Comment (suraj44) [inline internal/lockclient/simple_client_test.go]: same as above

File: internal/lockclient/simple_client_test.go [hunk 27]
```diff
@@ -99,40 +99,115 @@ func TestAcquireandRelease(t *testing.T) {
...
 			t.Errorf("release: got %q want %q", got, want)
 		}
 	})
+
 	quit <- true
 	return
 }
+
+// BenchmarkLocKeyWithoutCache stats:     2130	  28828088 ns/op	   15952 B/op	   190 allocs/op
+func BenchmarkLocKeyWithoutCache(b *testing.B) {
```
Comment (suraj44) [inline internal/lockclient/simple_client_test.go:140]: good stuff!

File: internal/lockservice/lockservice.go [hunk 28]
```diff
@@ -12,9 +12,10 @@ type LockService interface {
 	// An error is generated if the same isn't possible for any reason,
 	// including releasing locks on non-acquired descriptors.
 	Release(Descriptors) error
-	// CheckAcquire checks whether a lock has been acquired on the given descriptor.
+	// Checkacquire checks whether a lock has been acquired on the given descriptor.
```
Comment (suraj44) [inline internal/lockservice/lockservice.go]: why has only this function been made lowercase 'a'?

File: internal/lockservice/simpleLockService.go [hunk 29]
```diff
@@ -42,41 +54,56 @@ type SimpleLockService struct {
 	lockMap *SafeLockMap
 }
 
-var _ Descriptors = (*SimpleDescriptor)(nil)
+var _ Descriptors = (*LockDescriptor)(nil)
 
-// SimpleDescriptor implements the Descriptors interface.
+// ObjectDescriptor describes the object that is subjected to
+// lock operations.
+type ObjectDescriptor struct {
```
Comment (suraj44) [inline internal/lockservice/simpleLockService.go:61]: Why can't LockDescriptor be used in the cache-related functions?

File: internal/lockservice/simpleLockService.go [hunk 30]
```diff
@@ -88,7 +115,7 @@ func NewSimpleLockService(log zerolog.Logger) *SimpleLockService {
 	}
 }
 
-// Acquire function lets a client acquire a lock on an object.
+// Acquire function lets a client Acquire a lock on an object.
```
Comment (suraj44) [inline internal/lockservice/simpleLockService.go]: why is this change needed?

File: internal/lockservice/simpleLockService.go [hunk 31]
```diff
@@ -98,14 +125,15 @@ func (ls *SimpleLockService) Acquire(sd Descriptors) error {
 			Debug().
 			Str("descriptor", sd.ID()).
 			Msg("can't acquire, already been acquired")
-		return ErrFileAcquired
+		return ErrFileacquired
```
Comment (suraj44) [inline internal/lockservice/simpleLockService.go:128]: I don't understand the need for this change

File: internal/lockservice/simpleLockService.go [hunk 32]
```diff
@@ -146,44 +175,47 @@ func (ls *SimpleLockService) Release(sd Descriptors) error {
 
 }
 
-// CheckAcquired returns true if the file is acquired
-func (ls *SimpleLockService) CheckAcquired(sd Descriptors) bool {
+// CheckAcquired returns true if the file is Acquired.
+// It also returns the owner of the file.
+func (ls *SimpleLockService) CheckAcquired(sd Descriptors) (string, bool) {
```
Comment (suraj44) [inline internal/lockservice/simpleLockService.go:180]: This is super confusing. Having one function called checkacquired and the other checkAcquired()

They both have significantly different functionality, their naming scheme needs to be updated to reflect that

File: internal/routing/acquire.go [hunk 33]
```diff
@@ -48,21 +47,27 @@ func checkAcquired(w http.ResponseWriter, r *http.Request, ls *lockservice.Simpl
...
+	desc := &lockservice.LockDescriptor{
 		FileID: req.FileID,
-		UserID: req.UserID,
 	}
-	if ls.CheckAcquired(desc) {
-		w.Write([]byte("checkAcquire success"))
+
+	owner, ok := ls.CheckAcquired(desc)
+	if ok {
+		byteData, err := json.Marshal(lockservice.CheckacquireRes{Owner: owner})
```
Comment (suraj44) [inline internal/routing/acquire.go]: seriously. here lsCheck**A**cquired is called but the object is called Check**a**cquireRes

why??

**Review by suraj44 — CHANGES_REQUESTED** [review]

File: internal/cache/lru_cache.go (hunk 2 above)
Comment (SUMUKHA-PK) [reply internal/cache/lru_cache.go:51]: Ive mentioned this is old PR

File: internal/cache/cache.go (hunk 1 above)
Comment (SUMUKHA-PK) [reply internal/cache/cache.go:6]: Yep. It checks the object I want exists or not

File: internal/cache/lru_cache.go (hunk 3 above)
Comment (SUMUKHA-PK) [reply internal/cache/lru_cache.go:100]: Sure

File: internal/lockclient/client.go (hunk 7 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/client.go:9]: Should be somewhere in the future, not a priority just an enhancement.

File: run.sh (hunk 8 above)
Comment (SUMUKHA-PK) [reply run.sh:1]: Its deleted, thats what is shown.

File: internal/lockclient/client.go (hunk 10 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/client.go]: This is a lock watching thing, removed.

File: internal/lockclient/errors.go (hunk 11 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/errors.go]: Removed.

File: internal/lockclient/simple_client.go (hunk 12 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client.go]: Oops, I think someone copy pasted this.

File: internal/lockclient/simple_client.go (hunk 13 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client.go]: Oops, something from previous implementation I believe.

File: internal/lockclient/simple_client.go (hunk 14 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client.go]: `CheckAcquire` is checking whether the `file` is acquired or not. Seems okay because we need to hide the cache and behave as it was a network call.

File: internal/lockclient/simple_client.go (hunk 16 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client.go:84]: :P

File: internal/lockclient/simple_client.go (hunk 17 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client.go]: Oops yes.

File: internal/lockclient/simple_client.go (hunk 19 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client.go]: yep good catch!
I believe there were some other checks before and this stayed because others were removed and I overlooked

File: internal/lockclient/simple_client.go (hunk 20 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client.go:150]: Yep else we need to send a `""` which just looks bad. Moreover, this is used in multiple places and I think it deserves to be a datatype.

File: internal/lockclient/simple_client_test.go (hunk 21 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client_test.go]: Yep. This was when pounce existed.

File: internal/lockclient/simple_client_test.go (hunk 27 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client_test.go:140]: :P

File: internal/lockservice/simpleLockService.go (hunk 29 above)
Comment (SUMUKHA-PK) [reply internal/lockservice/simpleLockService.go:61]: Check #21

File: internal/lockservice/simpleLockService.go (hunk 32 above)
Comment (SUMUKHA-PK) [reply internal/lockservice/simpleLockService.go:180]: Um no. One is a method on the client and the other on the service. Must be OK.

File: internal/routing/acquire.go (hunk 33 above)
Comment (SUMUKHA-PK) [reply internal/routing/acquire.go]: Oops check the final comment xD

**Comment by SUMUKHA-PK** [comment]
Excellent excellent reviewing dude! We're upping the game like this. Im sure you learnt a lot and I did too. We're making our code neater and tighter with these reviews and learning with an excellent foundation for ourselves, lets keep it going!

PS: About the weird lower and upper case letter `A`'s xD, it was because I was moving `Acquire` to `acquire` and I did a global find and replace. Will fix them so that they make sense :)

File: internal/lockservice/simpleLockService.go (hunk 32 above)
Comment (SUMUKHA-PK) [reply internal/lockservice/simpleLockService.go:180]: This is my defence if you think thats still confusing(it shouldn't be and Im sure that's fine because they're methods of different structs):
`CheckAcquired` is checking in the LS whether the lock was acquired.
`CheckAcquire` is checking in the LC whether an `Acquire` call was made and it was successful.

Something like being in its own domain sort of thing.

File: internal/lockservice/lockservice.go (hunk 28 above)
Comment (SUMUKHA-PK) [reply internal/lockservice/lockservice.go]: Changed

File: internal/lockclient/simple_client.go (hunk 15 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client.go]: Im not sure what you mean. Please explain :D

File: internal/routing/routing.go (hunk 9 above)
Comment (SUMUKHA-PK) [reply internal/routing/routing.go]: Okay this will be my new philosophy - in the newer commit.

`make` will just prepend the function name.

File: internal/cache/lru_cache.go (hunk 5 above)
Comment (SUMUKHA-PK) [reply internal/cache/lru_cache.go:102]: What do you mean?

File: internal/cache/lru_cache.go (hunk 2 above)
Comment (SUMUKHA-PK) [reply internal/cache/lru_cache.go:51]: Ref: Since we might not return owner always, I think we should abstract what it returns. It returns whatever we store in it. Makes it robust that way.

File: internal/cache/lru_cache.go (hunk 4 above)
Comment (SUMUKHA-PK) [reply internal/cache/lru_cache.go:101]: This is very basic IMO, everyone will know that adding to an empty LL can be distinguished and can be done.

Comment (SUMUKHA-PK) [reply internal/cache/lru_cache.go:101]: Most of the ideology is mentioned in the start of the file.

File: internal/routing/routing.go (hunk 9 above)
Comment (suraj44) [reply internal/routing/routing.go]: what about for the endpoint? why is it 'checkacquire' but for release it is 'checkRelease' ?

File: internal/cache/lru_cache.go (hunk 5 above)
Comment (suraj44) [reply internal/cache/lru_cache.go:102]: @SUMUKHA-PK  `lru.dll.InsertNodeToRight(lru.dll.Head, element.(*SimpleKey))`
Is the main reason for this function call to make `lru.Head` point to the new element being inserted? Can this just be replaced with something like `lru.Head = element` ?

File: internal/lockclient/simple_client.go (hunk 14 above)
Comment (suraj44) [reply internal/lockclient/simple_client.go]: Ah okay got it. The element will be in the cache only if it is acquired. Still, maybe a different error would be useful for debugging in the future?

File: internal/lockclient/simple_client.go (hunk 15 above)
Comment (suraj44) [reply internal/lockclient/simple_client.go]: see the comment above :P

File: internal/cache/lru_cache.go (hunk 2 above)
Comment (suraj44) [reply internal/cache/lru_cache.go:51]: Makes sense.

File: internal/lockservice/simpleLockService.go (hunk 29 above)
Comment (suraj44) [reply internal/lockservice/simpleLockService.go:61]: Oh right. I'd forgotten why we did this.

File: internal/lockservice/simpleLockService.go (hunk 32 above)
Comment (suraj44) [reply internal/lockservice/simpleLockService.go:180]: Ah okay, yup makes sense.

File: internal/routing/acquire.go (hunk 33 above)
Comment (suraj44) [reply internal/routing/acquire.go]: @SUMUKHA-PK  does this need to be rectified?

File: internal/lockclient/simple_client.go (hunk 14 above)
Comment (SUMUKHA-PK) [reply internal/lockclient/simple_client.go]: I dont know whether we should. Still think it should be transparent, not sure what future needs might be.

File: internal/cache/lru_cache.go (hunk 5 above)
Comment (SUMUKHA-PK) [reply internal/cache/lru_cache.go:102]: No, node needs to created etc.

File: internal/routing/routing.go (hunk 9 above)
Comment (SUMUKHA-PK) [reply internal/routing/routing.go]: Changed

File: internal/routing/acquire.go (hunk 33 above)
Comment (SUMUKHA-PK) [reply internal/routing/acquire.go]: Done
